# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90179729a3ce8b9040605ea84a7d90ac2787f92eb86e437dbee8f9119fe97f7b594c7c40f0f031b0d266d5538579f4177f4f8f805c7fad29b4b12a857d011436

test:
  secret_key_base: 50db24303946edb9b95d7d962ead76f8a953391ffb5085f68ced3a622255b80bb6ca0045f6b0103b7da4326aa3f725e3edc3e168b6a2e3c03dc566c1e41fd1a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
